/* Name Section */
Between Time Template
/* Type Section */
DIAMOND_TEMPLATE
/* Var Section */
{'startHour':'undefined','startMinute':'undefined','endHour':'undefined','endMinute':'undefined'}
/* Var Types Section */
{'startHour':'INT','startMinute':'INT','endHour':'INT','endMinute':'INT'}
/* Code Section */
var now = new Date();
result = now.getHours() > vars.startHour || (now.getHours() == vars.startHour && now.getMinutes() > vars.startMinute)
result = result && (now.getHours() < vars.endHour || (now.getHours() == vars.endHour && now.getMinutes() < vars.endMinute))
/* Comment Section */
now >= ${startHour}:${startMinute} and now <= ${endHour}:${endMinute}